//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_elso_host.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eloado", Namespace="http://schemas.datacontract.org/2004/07/WCF_elso_sever")]
    [System.SerializableAttribute()]
    public partial class Eloado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int eloadoAzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eloadoNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eloadoAz {
            get {
                return this.eloadoAzField;
            }
            set {
                if ((this.eloadoAzField.Equals(value) != true)) {
                    this.eloadoAzField = value;
                    this.RaisePropertyChanged("eloadoAz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eloadoName {
            get {
                return this.eloadoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.eloadoNameField, value) != true)) {
                    this.eloadoNameField = value;
                    this.RaisePropertyChanged("eloadoName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zeneszam", Namespace="http://schemas.datacontract.org/2004/07/WCF_elso_sever")]
    [System.SerializableAttribute()]
    public partial class Zeneszam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZeneszamAzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZeneszamCimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZeneszamHosszField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZeneszamAz {
            get {
                return this.ZeneszamAzField;
            }
            set {
                if ((this.ZeneszamAzField.Equals(value) != true)) {
                    this.ZeneszamAzField = value;
                    this.RaisePropertyChanged("ZeneszamAz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZeneszamCim {
            get {
                return this.ZeneszamCimField;
            }
            set {
                if ((object.ReferenceEquals(this.ZeneszamCimField, value) != true)) {
                    this.ZeneszamCimField = value;
                    this.RaisePropertyChanged("ZeneszamCim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZeneszamHossz {
            get {
                return this.ZeneszamHosszField;
            }
            set {
                if ((this.ZeneszamHosszField.Equals(value) != true)) {
                    this.ZeneszamHosszField = value;
                    this.RaisePropertyChanged("ZeneszamHossz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CD", Namespace="http://schemas.datacontract.org/2004/07/WCF_elso_sever")]
    [System.SerializableAttribute()]
    public partial class CD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CdAzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdCimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KiadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdAz {
            get {
                return this.CdAzField;
            }
            set {
                if ((this.CdAzField.Equals(value) != true)) {
                    this.CdAzField = value;
                    this.RaisePropertyChanged("CdAz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CdCim {
            get {
                return this.CdCimField;
            }
            set {
                if ((object.ReferenceEquals(this.CdCimField, value) != true)) {
                    this.CdCimField = value;
                    this.RaisePropertyChanged("CdCim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kiado {
            get {
                return this.KiadoField;
            }
            set {
                if ((object.ReferenceEquals(this.KiadoField, value) != true)) {
                    this.KiadoField = value;
                    this.RaisePropertyChanged("Kiado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloado", ReplyAction="http://tempuri.org/IService1/GetEloadoResponse")]
        WCF_elso_host.ServiceReference1.Eloado GetEloado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloado", ReplyAction="http://tempuri.org/IService1/GetEloadoResponse")]
        System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.Eloado> GetEloadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloadoName", ReplyAction="http://tempuri.org/IService1/GetEloadoNameResponse")]
        string GetEloadoName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloadoName", ReplyAction="http://tempuri.org/IService1/GetEloadoNameResponse")]
        System.Threading.Tasks.Task<string> GetEloadoNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZeneszam", ReplyAction="http://tempuri.org/IService1/GetZeneszamResponse")]
        WCF_elso_host.ServiceReference1.Zeneszam GetZeneszam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZeneszam", ReplyAction="http://tempuri.org/IService1/GetZeneszamResponse")]
        System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.Zeneszam> GetZeneszamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCD", ReplyAction="http://tempuri.org/IService1/GetCDResponse")]
        WCF_elso_host.ServiceReference1.CD GetCD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCD", ReplyAction="http://tempuri.org/IService1/GetCDResponse")]
        System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.CD> GetCDAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_elso_host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_elso_host.ServiceReference1.IService1>, WCF_elso_host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_elso_host.ServiceReference1.Eloado GetEloado() {
            return base.Channel.GetEloado();
        }
        
        public System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.Eloado> GetEloadoAsync() {
            return base.Channel.GetEloadoAsync();
        }
        
        public string GetEloadoName() {
            return base.Channel.GetEloadoName();
        }
        
        public System.Threading.Tasks.Task<string> GetEloadoNameAsync() {
            return base.Channel.GetEloadoNameAsync();
        }
        
        public WCF_elso_host.ServiceReference1.Zeneszam GetZeneszam() {
            return base.Channel.GetZeneszam();
        }
        
        public System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.Zeneszam> GetZeneszamAsync() {
            return base.Channel.GetZeneszamAsync();
        }
        
        public WCF_elso_host.ServiceReference1.CD GetCD() {
            return base.Channel.GetCD();
        }
        
        public System.Threading.Tasks.Task<WCF_elso_host.ServiceReference1.CD> GetCDAsync() {
            return base.Channel.GetCDAsync();
        }
    }
}
